---
- name: Validate SOA Admin console
  hosts: oracle01
  tasks:
  - name: Validate Admin Console
    uri:
     url: http://3.93.52.125:7001/console 
     return_content: yes
    register: this
    failed_when: "'WebLogic Server Version: 12.2.1.2.0' not in this.content"
...
